# Generated by Django 3.1.2 on 2022-01-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productname', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('colour', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
